language: python
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gfortran-5
            - gcc-5
            - g++-5
            - cmake
            - mpich2
            - libgomp1

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install python-numpy python-matplotlib python-scipy

script:
    - ulimit -s unlimited
    - source sourceme.sh
    - export FC=/usr/bin/gfortran-5
    - export CC=/usr/bin/gcc-5
    - cd samples
    - export OMP_NUM_THREADS=1
    - ./magic_wizard.py --use-mpi --nranks 2 --use-openmp --nthreads 1 --level 0 --mpicmd mpirun
