language: python
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
              key_url: 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB'
        packages:
            - cmake
            - gcc
            - g++
            - pkg-config
            - build-essential
            - libgomp1
            - intel-oneapi-ifort
            - intel-oneapi-icc

before_install:
    - sudo wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list
    - sudo apt-get -qq update
    - sudo apt-get -y install python-numpy python-matplotlib python-scipy
    - sudo apt-get -y install intel-mpi-2019.6-088 # To make sure mpi is installed
                                                   # after intel suite 
    - sudo apt-get -y install intel-mkl-64bit-2020.0-088
    - source /opt/intel/inteloneapi/setvars.sh
    - source /opt/intel/compilers_and_libraries_2020/linux/bin/compilervars.sh intel64

script:
    - ulimit -s unlimited
    - source sourceme.sh
    - export FC=mpiifort
    - export CC=mpiicc
    - export CXX=mpiicpc
    - mpiifort --version
    - echo $MKLROOT
    - cd samples
    - ./magic_wizard.py --use-mpi --use-mkl --nranks 2 --level 0 --mpicmd mpiexec.hydra
