language: python
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gfortran
            - gcc
            - g++
            - cmake
            - liblapack-dev
            - liblapacke-dev
            - libfftw3-dev


before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install python-numpy python-matplotlib python-scipy
    - sudo apt-get -y install mpich libmpich-dev 

script:
    - ulimit -s unlimited
    - source sourceme.sh
    - export FC=mpif90
    - export CC=gcc
    - cd bin
    - ./install-shtns.sh
    - cd ../samples
    - ./magic_wizard.py --use-shtns --use-mpi --nranks 2 --level 0 --mpicmd mpiexec.hydra
