language: python
sudo: required

addons:
    apt:
        sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
        packages:
            - gfortran-5
            - gcc-5
            - g++-5
            - cmake
            - mpich2

before_install:
    - sudo apt-get -qq update
    - pip install numpy matplotlib scipy

script:
    - export FC=/usr/bin/gfortran-5
    - export CC=/usr/bin/gcc-5
    - mkdir cmake-build
    - cd cmake-build
    - cmake .. -DUSE_MPI=no
    - make -j 4
