language: python
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gfortran-5
            - gcc-5
            - g++-5
            - cmake
            - mpich2

before_install:
    - sudo apt-get -qq update
    - pip install numpy matplotlib scipy

script:
    - export FC=mpif90
    - export CC=mpicc
    - mkdir cmake-build
    - cd cmake-build
    - cmake ..
    - make -j 4
