language: python
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gfortran-5
            - gcc-5
            - g++-5
            - cmake

before_install:
    - sudo apt-get -qq update
    - pip install numpy matplotlib scipy
    - sudo apt-get install mpich2 -y

script:
    - export FC=/usr/bin/mpif90.mpich2
    - export CC=/usr/bin/mpicc.mpich2
    - mkdir cmake-build
    - cd cmake-build
    - cmake .. -DUSE_MPI=yes
    - make -j 4
