language: python
sudo: required

addons:
    apt:
        packages:
            - gfortran
            - gcc
            - g++
            - cmake

before_install:
    - sudo apt-get -qq update
    - pip install numpy matplotlib scipy
    - sudo apt-get install libmpich-dev mpich -y

script:
    - export FC=mpif90
    - export CC=mpicc
    - mkdir cmake-build
    - cd build
    - cmake .. -DUSE_MPI=yes
    - make -j 4
